# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        source-url: https://nuget.pkg.github.com/Voyager-Poland/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release
    - name: Pack
      run: dotnet pack --no-restore --no-build -c Release  /home/runner/work/Voyager.BackgroundWorker/Voyager.BackgroundWorker/src/Voyager.BackgroundWorker/Voyager.BackgroundWorker.csproj
    - name: ls
      run: ls  /home/runner/work/Voyager.BackgroundWorker/Voyager.BackgroundWorker/src/Voyager.BackgroundWorker/bin/Release/*.nupkg

#    - name: Publish the package to GPR
#      run: dotnet nuget push /home/runner/work/Voyager.BackgroundWorker/Voyager.BackgroundWorker/src/Voyager.BackgroundWorker/bin/Release/*.nupkg


